### ISSUE TITLE
After creating an image, it will not be loaded on the server.

### ISSUE THREAD

**Issue by mathiasrettich** [linuxmuster/linuxmuster-webui7#100]
Hello everybody,
Following situation:
I would like to create an image from a client via the Linbo console and immediately transfer it to the server. Subsequently, the client should shut down itself.
For this I go to Imaginig and choose Image erstellen.
![B001](https://user-images.githubusercontent.com/3775093/57019585-42197600-6c27-11e9-937f-f60d6a14d2c6.png)
As you can see in the screenshot, I choose Shutdown and click Erstellen+Hochladen.
Then the computer creates an image, but does not upload it, but switches off immediately.
Greeting,
Mathias

**Comment by zefanja** [comment]
It's a know issue: https://github.com/linuxmuster/linuxmuster-linbo/issues/65

PS: This bug is not related to the webui. For each main component, there is a separate repository, like linuxmuster-webui7, linuxmuster-linbo, sophomorix4, linuxmuster-base7, ... (https://github.com/linuxmuster). If you know to which repo your bug belongs, report it in the right repo. Thanks :)

**Comment by kiarn** [comment]
Not related to webui.
