### ISSUE TITLE
Devices List Validation 

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-webui7#103]
The devices List validation should be triggered on save, not as soon as the add button is clicked:

![Peek 2019-05-23 11-21](https://user-images.githubusercontent.com/26460239/58241550-7c20f800-7d4d-11e9-80d4-7b7330b70877.gif)

A similiar validation then could be added to student and teachers list as well.

**Comment by kiarn** [comment]
Ok.

**Comment by kiarn** [comment]
The first part is done.

> A similiar validation then could be added to student and teachers list as well.

I've seen your commit about [testing empty fields in the teachers list](https://github.com/linuxmuster/linuxmuster-webui7/blob/10319c26ef83c0e8e715cd17a68732e509a71e8a/usr/lib/linuxmuster-webui/plugins/lmn_users/resources/js/controllers/teachers-list.controller.coffee#L79). I think the TODO to add a red border line in the error fields would be easier in the angularjs way, I mean with [ng-class and data binding](https://github.com/linuxmuster/linuxmuster-webui7/blob/10319c26ef83c0e8e715cd17a68732e509a71e8a/usr/lib/linuxmuster-webui/plugins/lmn_devices/resources/partial/index.html#L58) instead of nested loop on the array. It would be the same code as in the device plugin.

Are you ok with this ?

**Comment by PLanB2008** [comment]
Yes of course, go ahead :)
