### ISSUE TITLE
No License text

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#11]
If you start the initial configuration with the webui there is just a placeholder text on the first screen. 

If you do the setup with via CLI you don't have to accept a license.

![auswahl_057](https://user-images.githubusercontent.com/708888/39814191-94af0e3a-53bd-11e8-9808-20df1419b40a.png)

**Comment by kiarn** [comment]
Hello,

[Ajenti](http://ajenti.org/) is distributed under MIT license AKA [License X11](https://en.wikipedia.org/wiki/MIT_License). From what I understand, the MIT License is more permissive than the GPL 3.0, mainly because of copyleft.

But, as seen of the official site of the FSF, [GPL 3.0 and MIT](https://www.gnu.org/licenses/license-list.en.html#X11License) seem to be [compatible](https://www.gnu.org/licenses/gpl-faq.en.html#WhatDoesCompatMean).

So I think we can use GPL 3.0 here, if the other dev are ok with this.

**Comment by zefanja** [comment]
Can't we just skip this screen? Maybe add a about page somewhere with infos for version, licence, ...

**Comment by PLanB2008** [comment]
I would at least keep it as a welcome screen.
