### ISSUE TITLE
Keine Filterung von Umlauten beim Anlegen von Kursen

### ISSUE THREAD

**Issue by dooomkopf** [linuxmuster/linuxmuster-webui7#117]
Unterricht -> Kurse anlegen -> Schüler hinzufügen:

SuS mit Umlauten oder é im Namen werden nicht gefunden.

**Comment by kiarn** [comment]
Hello,

Is it still a problem, because I cannot reproduce this : 

![2020-02-24_14-22](https://user-images.githubusercontent.com/10401079/75155985-6c39a880-5711-11ea-877c-b4136789c003.png)

![2020-02-24_14-22_1](https://user-images.githubusercontent.com/10401079/75156003-73f94d00-5711-11ea-9332-ec1248e79ecb.png)

Otherwise, I would close this issue.

Arnaud
