### ISSUE TITLE
User information should show the current used quota as well

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-webui7#132]
![grafik](https://user-images.githubusercontent.com/26460239/80605317-37104600-8a33-11ea-9363-a034ef285d98.png)

We should add a query which gets the current used quota for a user. Perhaps we can use the same code used for the landing pange and print a nice progressbar so an admin can have a look at the quota usage of a specific user.

Also we should work on an qupta overview, even if it would be very slow.

**Comment by kiarn** [comment]
It's already prepared in user list, see : 

https://github.com/linuxmuster/linuxmuster-webui7/blob/836a4e8c482a749a0e94710fd9fb51ac1e6e0b40/usr/lib/linuxmuster-webui/plugins/lmn_users/resources/partial/teachers.html#L140

and 

https://github.com/linuxmuster/linuxmuster-webui7/blob/836a4e8c482a749a0e94710fd9fb51ac1e6e0b40/usr/lib/linuxmuster-webui/plugins/lmn_users/resources/js/controllers/teachers.controller.coffee#L53

With this method is it possible to call the quota if necessary.

About the quota overview, it's on my todo list since the beginning, I really need it :)

**Comment by kiarn** [comment]
I add a raw view of quota, please see : https://github.com/linuxmuster/linuxmuster-webui7/commit/cb635c0f5ee312d5d758c55a8c0e8e3e247829b4

![user3](https://user-images.githubusercontent.com/10401079/81441497-2b7af880-9172-11ea-949c-5dcf49f76370.png)

There's already a little overview of the quotas in the teacher view --> Show quotas bottom right.
This is not implemented for the students, and maybe not really good for this, I let you have a look at this.

![user2](https://user-images.githubusercontent.com/10401079/81441512-32097000-9172-11ea-8c9a-7a48b86809d7.png)

Another question : is it necessary to have a difference between "User settings" and then "User info" in the user view ?
It's really annoying to have to clic 2 times to get the user details, but maybe there's something planned I don't know.

![user1](https://user-images.githubusercontent.com/10401079/81441526-36358d80-9172-11ea-9726-4e9333b88733.png)

**Comment by kiarn** [comment]
And also please see : https://github.com/linuxmuster/linuxmuster-webui7/commit/2e83c23eb4c7566c62949a5bd8adcd7bfbde8b5b

**Comment by kiarn** [comment]
Already done.
