### ISSUE TITLE
Migrate OS icons from .png to .svg

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#162]
Hello again,

The new Linbo GUI uses .svg icons instead of .png.
It would be nice to use these new icons in the webui as well.
(over here)
![OsIcons](https://user-images.githubusercontent.com/30153207/102925139-25cceb80-4493-11eb-9915-d68036b01d7a.png)

All the new Icons can be found over here: [https://github.com/linuxmuster/linuxmuster-linbo-gui/tree/master/build/icons](https://github.com/linuxmuster/linuxmuster-linbo-gui/tree/master/build/icons)

Thanks in advance :)

Regards
Dorian

**Comment by kiarn** [comment]
Hello @CodeCrafter912,

For this, I think we should ensure the compatibility with all linbo versions and first check which linbo version use svg instead of png. Is it for `linuxmuster-linbo7` up to 2.4.1 or only if `linuxmuster-linbo-gui7` is installed ?

Regards,

Arnaud

**Comment by kiarn** [comment]
One more thing : all icons was always present in `/srv/linbo/icons/` (or `/srv/linbo/boot/grub/themes/linbo/icons/` ?) through the package `linuxmuster-linbo7`.
I just checked that the webui always lists the icons of `/srv/linbo/icons/`, and it may be wrong since months, can someone please confirm this is the right directory ? (@HappyBasher ?)

So, if we want to list the new svg icons in the webui, it would be nice to add these in an subdirectory of `/srv/linbo`.

Regards,

Arnaud

**Comment by dorianim** [comment]
Hi @kiarn 

This just applies to linuxmuster-linbo-gui7.

Maybe it would make sense to keep both icon formats until only the new GUI ist supported? 
I am not sure how to implement that cleanly though...

**Comment by kiarn** [comment]
Hi @CodeCrafter912 

> This just applies to linuxmuster-linbo-gui7.

Ok, then it is possible to check whenever this package is installed, and then use svg instead of png.
 
> Maybe it would make sense to keep both icon formats until only the new GUI ist supported?
> I am not sure how to implement that cleanly though...

You can see an example in the linbo repo : 

- all icons are stored in https://github.com/linuxmuster/linuxmuster-linbo/tree/master/files/common/var/linbo
- the content of this directory is copied in the deb package, and then extracted through the install process : https://github.com/linuxmuster/linuxmuster-linbo/blob/d5576d6f58d98804cb1b208725525ba802a723e6/debian/rules#L689

But I think it's better to clarify this with @HappyBasher.
