### ISSUE TITLE
Setup Wizard Checking Servers Issue

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-webui7#186]
When checking the docker and opsi server the setup wizard tries to establish an ssh connection.

This only works if the ssh key exchange has already been done. 
At this point there is no ssh private key on the server. Essentially the check should try the default password for the ssh authentication 'Muster!'

At the moment we use the ssh command to achieve this but the ssh command cannot receive a cleartext password via argument. Using sshpass would be an option, but I think using a native python module would work better.

**Comment by kiarn** [comment]
Hello @PLanB2008 

I've added a basic test in `tools.py` using `paramiko`, and I let the examples.
It seems to work on my test system, but please test it again to see if it solves your problematic.

There's an additional variable `err` in order to describe the error if the ssh connection failed, but this is currently not used.

**Comment by kiarn** [comment]
Hello @PLanB2008 

Does this works as it should ?

**Comment by PLanB2008** [comment]
Ya this seems to work. I'm not sure if there's still another issue regarding the setup wizard but the ssh issue is fixed so we can definitely close the issue.
