### ISSUE TITLE
Unify management of "special" users?

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#200]
Hi,

![image](https://user-images.githubusercontent.com/30153207/140602319-874e523a-0d13-4cf8-a860-f1114f2531f9.png)

Currently, there are two menu entries, one for global admins and one for school admins. Wouldn't it make sense to combine those two?
I think, they could be combined to something like "special users". In this entry, it could then also be possible to manage custom bind users.

What do you think? :slightly_smiling_face: 

Regards,
Dorian

**Comment by kiarn** [comment]
Hi,

We had this discussion some years ago to split admins + teachers + students in order to have a direct access to all roles. It's quite important to have a direct access to teachers and students, but I also really think we could merge all the admin together since it's not pretty often used.

What do the others think about it ?

Arnaud

**Comment by dorianim** [comment]
Yes, I fully agree :)

**Comment by dorianim** [comment]
> What do the others think about it ?

@PLanB2008 @jeffbeck @HappyBasher

**Comment by dorianim** [comment]
Thanks for implementing the binduser management, works fine for me :+1: 
Another nice feature would be to show the generated password (stored in `/etc/linuxmuster/.secret/<username>`) :slightly_smiling_face:

**Comment by kiarn** [comment]
Even if I think it's a little security issue, it's done.
Only admins can see this, and I try to harden this enough.

Unifying the admins views will not be done at the moment (we found no consensus), we can speak about it by the next dev meeting.

Arnaud
