### ISSUE TITLE
Allow some Devices to have too long hostnames

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#207]
Hi,

I think, long hostnames should be allowed for devices other than `Schüler-PC im Klassenzimmer`, `Lehrer-PC im Klassenzimmer`, `Lehrer-PC`, `Fakultäts-Computer` and `domänencontroller`. 
I think, I's not necessary to enforce this for all other types.

Regards,
Dorian

**Comment by kiarn** [comment]
Hi,

Yes I agree. But this may causes some problems because we can't know which computer in which group will join the domain : this is all in the hand of the local admin, and can mess up some computers on his network if he/she doesn't pay enough attention. This must be good documented and communicated.

BTW, can you explain in which cases 15 chars are not enough ? 
Do you have subdomains ?

Arnaud

**Comment by dorianim** [comment]
> BTW, can you explain in which cases 15 chars are not enough ?

We just have some longer names, eg:
- `ELE-wetterstation`
- `server-hypervisor`
- `server-rocketchat`

They could be shortened, of course, but it's a bit annoying since these devices are never going to be joined to a domain. I think it is enough to catch this mistake for Computers, since most users probably only ever join a computer and no server.

**Comment by kiarn** [comment]
There's some other use cases with a server joining a domain, like ldap-replica, DFS, etc ... but these cases are mostly reserved for advanced users or company, and I don't remember if they are mentioned in the `devices.csv`. 

The problem I have here is that I have no access to the role when I make a test about the hostname, I must show if this is possible in a simple way.
