### ISSUE TITLE
Fields editable by user

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-webui7#226]
Maybe we can add an option to allow users (especially teachers)  to edit custom fields which are defined by the admin as editable.

**Comment by kiarn** [comment]
Hello,

Do you mean to add an option for each to make it editable ?
Or should we let the admin decide which fields come to the landing page and let this way the users changing it ?
Or both ?
This is feasible, but need some work.

Arnaud

**Comment by PLanB2008** [comment]
I was thinking the second. Its not urgent in my opinion but would improve using custom fields for some use cases.

**Comment by kiarn** [comment]
Hello,

It is mostly done, but I have a permission problem : teachers and students should be able to read the configuration in `/etc/linuxmuster/sophomorix/SCHOOL/custom_fields.yml`, and it's not the case yet.
It's also not possible to read this config at startup and to store it in a variable because it depends on the school context. For the moment, I don't have an idea to solve it.

Arnaud

**Comment by kiarn** [comment]
This is fixed for teachers. Students need sudo permissions for `sophomorix-user` to edit these (it's only displayed actually), but I close it anyway.
