### ISSUE TITLE
List Management Empty entries get manipulated

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-webui7#252]
When for example, a user uploads a student file containing empty rows respecting the columns, so there are lines like this:

;;;;;;

This works initially. But when the user hits Save and Apply these empty lines get replaces by just blank lines. This again makes sophomorix uncumfortbale and leads to an sophomorix crash because there are empty lines.

Webui should either leave these lines as they are, or remove these empty lines all together.

This is a pretty rare corner case which happend to me last week.

**Comment by kiarn** [comment]
Hello @PLanB2008 

I made a test with the following `students.csv` and uploaded it as custom csv :

```
10a;Ilkes;Judith;28.04.1985;

10a;Imbrogiana;Henriette;16.06.1986;


10a;Krüger;Richard;30.06.1986;

;;;;

``` 

It's not possible to make a `Save & Apply` with it, because the validation service detects errors:

![20221006-172249](https://user-images.githubusercontent.com/10401079/194353338-4683df54-a875-46e7-a2f0-38540c19be64.png)

Manually launching a `sophomorix-check` and then a `sophomorix-update` do not lead to any error, so I don't understand what you mean with sophomorix crash. Can you please provide more details ?

Having lines with only semi-colon (or empty lines) will be a problem for the validation service and must be corrected, but it seems that the empty lines are accepted in `devices.csv`, but not in the user's CSV for list management ?

Arnaud

**Comment by PLanB2008** [comment]
I assume the validation does not work if you have a really long stundents.csv.

Ill provide you a list for testing purpose so you can debug this issue further.

**Comment by kiarn** [comment]
If the CSV is very long, you possibly can hit the `field_size_limit` : https://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072

But I thought it was already corrected this summer : https://github.com/linuxmuster/linuxmuster-webui7/blob/a2050aef2d4f8e02e67d7e0d83d1b37c22672230/usr/lib/linuxmuster-webui/plugins/lmn_common/lmnfile.py#L17

Arnaud

**Comment by kiarn** [comment]
Is this issue solved ?

**Comment by kiarn** [comment]
@PLanB2008 can we close it ? ;)
