### ISSUE TITLE
WebUI7: Can't show up devices

### ISSUE THREAD

**Issue by cweikl** [linuxmuster/linuxmuster-webui7#71]
I installed the WebUI (Version 1.0.23-1) on a lmn7 server (linuxmuster-base7 Version 7.0.24). The server has some users I have imported some devices via console which are working with linbo.
Working as user root in the WebUI an klicking the menue "Devices" I receive an server error indicating that there is likely a big (GET /api/lm/devices).

Chris

**Comment by zefanja** [comment]
Could you post the error message or a screenshot of the error, please?

**Comment by PLanB2008** [comment]
First things first:
There is a general problem we've to address in the documentation and after the installation process:

Working in webui as root is a bad idea. You should definitely use the created global-admin account. We're looking into the option of disabling root login for the webui.

Anyway, the reason for your problem seems to be different. I assume there's something wrong  either with the format your devices.csv or with the process webui tries to render the columns.

 In addition to the error message screenshot could you please add your devices.csv?

**Comment by cweikl** [comment]
Ok, I should use global-admin.
As I logged in again as root as I wanted to make a screenshot of the error, now the devices are shown.
Mmh, strange.
Please find attached the devices .csv
[devices.zip](https://github.com/linuxmuster/linuxmuster-webui7/files/2742032/devices.zip)

**Comment by kiarn** [comment]
Hello,

I tried your devices.csv on my installation, and there was no error. Is it still a problem ?

**Comment by cweikl** [comment]
I tested to import my device list by using WebUI (installed linuxmuster-base 7.0.31 and linuxmuster-webui7 1.0.56-1) again. I accessed the WebUI as the global-admin and then I saved & imported this device list. There were no errors anymore.
Closed.
