### ISSUE TITLE
End of setup wizard does not reload on "Close"

### ISSUE THREAD

**Issue by RolandBBerlin** [linuxmuster/linuxmuster-webui7#91]
The Final message of the setup wizard informs, that on close the webui will reload the secure webui. However, a message is shown "Restart Webui" without reloading the web page.

**Comment by jolly-jump** [comment]
True, happens to me too.

The idea would be to load a different URL, actually. Before: http://10.0.0.1:8000, after: https://hostname.domain:8000

**Comment by PLanB2008** [comment]
This would only work once the administrators client pc is using the LMN server as a DNS server. At this state we can't assume this.

It should be possible just to redirect from  http://10.0.0.1:8000 to https://10.0.0.1.8000 but we have to debug this a little more.

**Comment by kiarn** [comment]
Hello @PLanB2008 ,

I have already a solution for this, but not already pushed because I wanted to test further after the [hostname/servername problem have been resolved](https://github.com/linuxmuster/linuxmuster-base7/issues/67).

The problem is the following : when webui restart and serve https instead of http, then is the used websocket dead, and any command after the restart will be ignored.

Maybe a solution : 

1) $timeout(redirect --> https, 5000)  : redirect after 5s, this is saved in the browser
2) webui restart through http.get.

I try to push it this week-end.

Another solution would be to serve a static html page with timeout, but it is more work.

**Comment by PLanB2008** [comment]
Another solution would be to skip the forward at all and provide a link the user has to click after the webui restart is done.
Not really elegant but it would work I guess.

**Comment by kiarn** [comment]
I did a restart from the Webui with redirect to https://10.0.0.1:8000 here : https://github.com/linuxmuster/linuxmuster-webui7/commit/fdd3a0c5d92409577822f7f5bdb14aaedeb80cad

It worked on my test system, is this change not ok ?

**Comment by PLanB2008** [comment]
This is confirmed to work now.
